name: Android CI Build

on:
  push:
    branches: [ "principal" ] # Verifique se sua branch é 'principal' ou 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # PASSO 1: Descompacta o seu arquivo ZIP (usando o nome que está no seu repositório)
    - name: Unzip Project Files
      run: unzip AviatorAssist.zip
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # PASSO 2: Compilação usando o caminho completo para a pasta AviatorAssist-main
    - name: Build debug APK
      run: |
        # Usamos AviatorAssist-main como o nome da pasta de projeto mais provável após o unzip
        chmod +x AviatorAssist-main/gradlew 
        ./AviatorAssist-main/gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: AviatorAssist-APK
        # Caminho completo do APK dentro da pasta descompactada
        path: AviatorAssist-main/app/build/outputs/apk/debug/app-debug.apk
