name: Android CI Build

on:
  push:
    branches: [ "principal" ] # OU main, dependendo da sua branch padrão
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # PASSO 1: Descompacta o seu arquivo ZIP, criando a pasta AviatorAssist/
    - name: Unzip Project Files
      run: unzip AviatorAssist.zip
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # PASSO 2: Entra na pasta do projeto, dá permissão e executa a compilação
    - name: Build debug APK
      run: |
        cd AviatorAssist
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: AviatorAssist-APK
        # O caminho do APK deve incluir a pasta AviatorAssist
        path: AviatorAssist/app/build/outputs/apk/debug/app-debug.apk
        
