name: Android CI Build

on:
  push:
    branches: [ "principal" ] # Verifique se sua branch é 'principal' ou 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # PASSO 1: Descompacta o seu arquivo ZIP
    - name: Unzip Project Files
      run: unzip AviatorAssist.zip
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # PASSO 2: Compilação usando o caminho CORRETO: AviatorAssist/
    - name: Build debug APK
      run: |
        # Dá permissão de execução ao gradlew dentro da pasta AviatorAssist/
        chmod +x AviatorAssist/gradlew 
        # Executa o build a partir da pasta AviatorAssist/
        ./AviatorAssist/gradlew assembleDebug

    # PASSO 3: Upload do APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: AviatorAssist-APK
        # Caminho completo do APK dentro da pasta descompactada
        path: AviatorAssist/app/build/outputs/apk/debug/app-debug.apk
